### PR TITLE
Adding Registration.php

### PR DESCRIPTION
**Pull request by bayjohnpaul**
I'm adding a registration button on your login page, please review the code I made. I'm honor if you make me as one of the contributor of this project. Thanks in advance!

### CODE REVIEW

**Comment by bayjohnpaul** [comment]
I didn't put the position during registration because base on the issue [https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/issues/47]  there's a superadmin who can monitor all of the other admins and he/she is the only one who are able to put positions of the new or other admins.

**Comment by kishor10d** [comment]
@bayjohnpaul : Your PR not meeting MVC architecture of CodeIgniter framework. If I merge it, it will not work as expected and results in breakage of application.
Please check MVC architecture of CodeIgniter framework, recode your code and then raise PR.
Thanks a lot for using repository and thanks a ton to try to improve it.

**Comment by trueman61** [comment]
Not working!!

**Comment by kishor10d** [comment]
@trueman61: The registration functionality not added.

**Pull request closed without merging**
