### PR TITLE
updated registration.php

### PR DESCRIPTION
**Pull request by bayjohnpaul**
This is the updated registration.php. I added a register button at view login.php. 

[registration.txt](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/files/2660733/registration.txt)

### CODE REVIEW

**Comment by bayjohnpaul** [comment]
Added Registration.php as a controller for view registration.php

this is the code..
[registration_controller.txt](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/files/2660743/registration_controller.txt)

**Comment by bayjohnpaul** [comment]
Added a route for registration

this is the updated code for route..
[routes.txt](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/files/2660744/routes.txt)

**Comment by bayjohnpaul** [comment]
please review the updated code.

**Comment by kishor10d** [comment]
Still your code is not meeting the CodeIgniter standards.
First you commit the code in your fork. Test it and check for standards thoroughly.

**Comment by bayjohnpaul** [comment]
What do you mean by standard? Can you please give me example? Thanks in advance, im still a beginner trying to learn more about codeigniter. Hope you understand

**Pull request closed without merging**
